### ISSUE TITLE
Finding highway names

### ISSUE THREAD

**Issue by rythmkraze** [paulmach/slide#3]
Hi Paul

I have hundreds and thousands of data points coming from all over India from several hundred users, who are travelling either within cities or between cities. 

I wish to extract highway names for all the users who are travelling between cities(after ignoring data points from within city limits)

Is slide useful for this purpose? or is there any other tool or library/service that you recommend.

**Comment by EwenH** [comment]
rythmkraze, 
   This would probably not be available due to Strava wanting to hold on to proprietary data and that if your users are not exercising then Strava is not the product to interrogate. I would see that the Open Street Map API would be your friend here by passing it a lat/lng and returning the address which hopefully has the road name. 

I have done this for identifying the nearest road/track for lightning strikes however due to the rough country and lack of local OSM editors with local knowledge, this was very hit and miss but if you are looking at highways it should be good.

**Comment by rythmkraze** [comment]
Hi Paul,
Apologies for being unresponsive. I had moved away from the project that required this library and hence the silence. Thank you for your response. I am closing this out.
